### ISSUE TITLE
Cannot retrieve data from getContactEntityByName(String s) 

### ISSUE THREAD

**Issue by SigmaOne** [SigmaOne/TaskManager-Portlet#7]
Unexpected token: разработки near line 1[select c from elcom.entities.Contact c where c.content = name surname]
shit, man :shipit:

**Comment by Vergir** [comment]
Dear SigmaOne,

Thank you for your input. We will start working on you issue as soon as possible.

Best regards,
TaskManager-Portlet dev. team

**Comment by SigmaOne** [comment]
Dear SigmaOne, I fixed it!

Best regards,
TaskManager-Portlet dev. team
