### ISSUE TITLE
Sometimes on EditTask-tab, at some really random selectOneMenu(!), default selected value is not being mapped correctly.

### ISSUE THREAD

**Issue by SigmaOne** [SigmaOne/TaskManager-Portlet#8]
I figured it out! It's because getEmployeeOptions() returns not full set of Employees.

**Comment by Vergir** [comment]
I think we need to adapt some common bug-description format. Something like
1. Bug Name
2. Detailed description
3. Expected behaviour 
4. Actual behaviour
5. How to reproduce

Especially last part

**Comment by Vergir** [comment]
Can't fix this since "Edit task" button doesn't work (on develop branch)
